apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "demo"
spec:
  title: "DCAI Sandbox"
  description: "DCAI Sandbox/Demo enviroment"
  publish:
    image: "$(image_repository)/demo-files:$(workshop_version)"
  workshop:
    files:
    - image:
        url: "$(image_repository)/demo-files:$(workshop_version)"
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    namespaces:
      #security:
        #policy: baseline
      budget: x-large
    applications:
      terminal:
        enabled: true
        #layout: split
      editor:
        enabled: true
      console:
        enabled: true
      docker:
        enabled: false
      registry:
        enabled: false
      vcluster:
        enabled: false
