apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "demo"
spec:
  title: "DCAI Sandbox"
  description: "DCAI Sandbox/Demo enviroment"
  publish:
    image: "$(image_repository)/demo-files:$(workshop_version)"
  workshop:
    files:
    - image:
        url: "$(image_repository)/demo-files:$(workshop_version)"
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    patches:
      runtimeClassName: nvidia
    namespaces:
      budget: x-large
      security:
        policy: baseline
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      console:
        enabled: false
      docker:
        enabled: false
      registry:
        enabled: false
      vcluster:
        enabled: false
    ingresses:
    - name: jupiter
      port: 8888
    dashboards:
    - name: Jupiter
      url: "$(ingress_protocol)://jupiter-$(session_name).$(ingress_domain)/lab?token=''"
    objects:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ollama
      spec:
        replicas: 1
        selector:
          matchLabels:
            deployment: ollama
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              deployment: ollama
          spec:
            runtimeClassName: nvidia
            containers:
            - name: ollama
              image: ollama/ollama:latest